# Generated by Django 3.2.5 on 2021-07-19 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot_summary', models.CharField(max_length=1000)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('director', models.CharField(max_length=50)),
            ],
        ),
    ]
